// Writes python/src/tcxp/_data.py from tcxp.js, so the Python package carries exactly the
// same registries, seed data, addresses and operator tables as the JavaScript engine.
// Usage: node python/tools/gen_data.mjs   (CI checks that the output is unchanged)
import {createRequire} from 'module';
import fs from 'fs';
const T = createRequire(import.meta.url)('../../tcxp.js');

function py(v, ind = '') {
  if (v === null || v === undefined) return 'None';
  if (v === true) return 'True';
  if (v === false) return 'False';
  if (typeof v === 'number') {
    if (!Number.isFinite(v)) throw new Error('non-finite number in data');
    return Number.isInteger(v) ? String(v) : String(v).includes('e') ? 'float(' + JSON.stringify(String(v)) + ')' : String(v);
  }
  if (typeof v === 'string') return JSON.stringify(v);
  const inner = ind + '    ';
  if (Array.isArray(v)) {
    if (!v.length) return '[]';
    const flat = v.every(x => x === null || typeof x !== 'object');
    if (flat) return '[' + v.map(x => py(x)).join(', ') + ']';
    return '[\n' + v.map(x => inner + py(x, inner)).join(',\n') + ',\n' + ind + ']';
  }
  const keys = Object.keys(v);
  if (!keys.length) return '{}';
  return '{\n' + keys.map(k => inner + JSON.stringify(k) + ': ' + py(v[k], inner)).join(',\n') + ',\n' + ind + '}';
}

// CSV-backed registries (src/data_csv.js) are rebuilt in Python by register_csv at import, exactly as
// tcxp.js builds them, so they are exported as their CSV source rather than as finished tables.
const csvSrc = fs.readFileSync(new URL('../../src/data_csv.js', import.meta.url), 'utf8');
const literal = (re, what) => { const m = re.exec(csvSrc); if (!m) throw new Error('data_csv.js: cannot find ' + what); return m[1]; };
const CLIENT_CSV = literal(/const CLIENT_CSV = `([^`]*)`;/, 'CLIENT_CSV');
const clientBase = new Function('return ' + literal(/REGISTRIES\['client\.demo'\] = (\{[\s\S]*?\}\});/, "REGISTRIES['client.demo']"))();
const clientTypes = new Function('return ' + literal(/registerCSV\('client\.demo', 'client_hours', CLIENT_CSV, (\{[^}]*\})\);/, 'registerCSV call'))();
const CSV_SOURCES = [['client.demo', 'client_hours', CLIENT_CSV, clientTypes]];
const csvBuilt = new Set(CSV_SOURCES.map(c => c[0]));

// Registries without their JS functions; the Python module attaches its own implementations.
const registries = {};
for (const [name, reg] of Object.entries(T.REGISTRIES)) {
  const r = {title: reg.title, description: reg.description};
  if (csvBuilt.has(name)) { registries[name] = {title: clientBase.title, description: clientBase.description, fns: {}, notes: clientBase.notes}; continue; }
  if (reg.db) r.db = {schema: reg.db.schema, seed: reg.db.seed};
  r.fns = {};
  for (const [path, f] of Object.entries(reg.fns)) r.fns[path] = {params: f.params, returns: f.returns, doc: f.doc};
  r.notes = reg.notes;
  registries[name] = r;
}

const out = [
  '# Generated by python/tools/gen_data.mjs from tcxp.js. Do not edit by hand.',
  '# fmt: off',
  'from typing import Any, Dict, List',
  '',
  'REGISTRIES_DATA: Dict[str, Any] = ' + py(registries),
  '',
  'QUERIES: List[Dict[str, Any]] = ' + py(T.QUERIES),
  '',
  'CSV_SOURCES: List[List[Any]] = ' + py(CSV_SOURCES),
  '',
  'GROUPS: List[List[str]] = ' + py(T.GROUPS),
  '',
  'COVERAGE: List[List[Any]] = ' + py(T.COVERAGE),
  '',
  'OPS: Dict[str, Dict[str, Any]] = ' + py(T.OPS),
  '',
  'CLAUSES: Dict[str, Dict[str, Any]] = ' + py(T.CLAUSES),
  '',
  'CLAUSE_ORDER: List[str] = ' + py(T.CLAUSE_ORDER),
  '',
  'WRITE_CLAUSES: Dict[str, Dict[str, Dict[str, Any]]] = ' + py(T.WRITE_CLAUSES),
  '',
  'WRITE_ORDER: Dict[str, List[str]] = ' + py(T.WRITE_ORDER),
  '',
  'RULES: List[List[str]] = ' + py(T.RULES),
  '',
  'FACETS: List[str] = ' + py(T.FACETS),
  '',
  'SCHEME: str = ' + py(T.SCHEME),
  '',
  'DEBOUNCE_MS: int = ' + py(T.DEBOUNCE_MS),
  ''
].join('\n');
fs.writeFileSync(new URL('../src/tcxp/_data.py', import.meta.url), out);
console.log('wrote python/src/tcxp/_data.py', out.length, 'bytes');
